In [3]:
import numpy as np

In [11]:
# Create a list
my_list = [534, 5468, 6546, 542, 9856, 4125]

### Create a ndarray from the regimentSize list

In [12]:
nparray = np.array(my_list)

### What are the number of dimensions of the array?

In [13]:
nparray.shape

(6,)

In [14]:
nparray.ndim

1

### Create Multidimensional Arrays 

In [17]:
my_list1 = [4277, 24368, 2546, 1542, 576, 285]

### Create a ndarray from a nested list

In [18]:
nparray = np.array([my_list, my_list1])

In [19]:
nparray

array([[  534,  5468,  6546,   542,  9856,  4125],
       [ 4277, 24368,  2546,  1542,   576,   285]])

In [20]:
nparray.shape

(2, 6)

### Generating Random Numbers With Numpy

### Generate A Random Number From The Normal Distribution

In [21]:
np.random.normal()

-1.589918702493253

### Generate Multiple Random Numbers From The Normal Distribution

In [22]:
np.random.normal(size=4)

array([ 0.79291036,  0.4688816 ,  0.72780739,  0.11383578])

### Generate Four Random Numbers From The Uniform Distribution

In [23]:
np.random.uniform(size=4)

array([ 0.76042978,  0.25426759,  0.01660121,  0.80156425])

### Generate Four Random Integers Between 1 and 100

In [24]:
np.random.randint(low=1, high=100, size=4)

array([24,  4, 16, 75])

### Create an Array of Zeroes and Range Generator

In [27]:
npzeroes = np.zeros(6)
npzeroes

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [30]:
# Create a range from 0 to 100
zero_to_99 = np.arange(0, 100)
zero_to_99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Create 100 ticks between 0 and 1

In [31]:
zero_to_1 = np.linspace(0, 1, 100)
zero_to_1

array([ 0.        ,  0.01010101,  0.02020202,  0.03030303,  0.04040404,
        0.05050505,  0.06060606,  0.07070707,  0.08080808,  0.09090909,
        0.1010101 ,  0.11111111,  0.12121212,  0.13131313,  0.14141414,
        0.15151515,  0.16161616,  0.17171717,  0.18181818,  0.19191919,
        0.2020202 ,  0.21212121,  0.22222222,  0.23232323,  0.24242424,
        0.25252525,  0.26262626,  0.27272727,  0.28282828,  0.29292929,
        0.3030303 ,  0.31313131,  0.32323232,  0.33333333,  0.34343434,
        0.35353535,  0.36363636,  0.37373737,  0.38383838,  0.39393939,
        0.4040404 ,  0.41414141,  0.42424242,  0.43434343,  0.44444444,
        0.45454545,  0.46464646,  0.47474747,  0.48484848,  0.49494949,
        0.50505051,  0.51515152,  0.52525253,  0.53535354,  0.54545455,
        0.55555556,  0.56565657,  0.57575758,  0.58585859,  0.5959596 ,
        0.60606061,  0.61616162,  0.62626263,  0.63636364,  0.64646465,
        0.65656566,  0.66666667,  0.67676768,  0.68686869,  0.69

### Indexing and Slicing Numpy Arrays

In [32]:
# Create a 2x2 array
battle_deaths = [[344, 2345], [253, 4345]]
deaths = np.array(battle_deaths)
deaths

array([[ 344, 2345],
       [ 253, 4345]])

In [33]:
# Select the top row, second item
deaths[0, 1]

2345

In [37]:
# Select the second column
deaths[:, 1]

array([2345, 4345])

In [48]:
# Select the second row
deaths[1, :]

array([ 253, 4345])

### Applying Conditions Using np.where() 

In [49]:
few_deaths = np.where(deaths[1,:] > 500)

In [50]:
few_deaths

(array([1], dtype=int64),)

#### Lets try that on a single-dimension array

In [54]:
death_count = [2131,534,3453,57,12432,4542,1241,5457]

In [55]:
death_count = np.array(death_count)

In [56]:
few_deaths = np.where(death_count<3000)

In [57]:
few_deaths

(array([0, 1, 3, 6], dtype=int64),)

### Find out Mean

In [58]:
death_count.mean()

3730.875

### Find out Sum

In [59]:
death_count.sum()

29847

### Min and Max

In [60]:
death_count.min()

57

In [62]:
death_count.max()

12432

### More Slicing and Indexing

In [70]:
# Divide the array of battle deaths into start, middle, and end of the war
warStart = death_count[0:2]; print('Death from battles at the start of war:', warStart)
warMiddle = death_count[2:4]; print('Death from battles at the middle of war:', warMiddle)
warEnd = death_count[4:7]; print('Death from battles at the end of war:', warEnd)

Death from battles at the start of war: [11101   534]
Death from battles at the middle of war: [3453   57]
Death from battles at the end of war: [12432  4542  1241]


## Broadcasting

### Change Value using Array Index

In [71]:
# Change the battle death numbers from the first battle
warStart[0] = 11101

In [72]:
warStart

array([11101,   534])

In [73]:
# View that change reflected in (i.e. "broadcasted to) the original death_count array
death_count

array([11101,   534,  3453,    57, 12432,  4542,  1241,  5457])

### Create a multidimensional array which behaves like a dataframe or matrix (i.e. columns and rows)

#### Create an array of fraternity brother information

In [ ]:
brother_names = ['Glory', 'Mark', 'Lauren', 'Jelena', 'Kristina']
age = [20, 21, 21, 20, 21]
major = ["Marketing", "MIS", "Accounting", "Economics", "Finance"]
year = [4, 3, 4, 3, 4]

regiments = np.array([regimentNames, regimentNumber, regimentSize, regimentCommander])
regiments